practice_copy/whiskey/project/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

###########################################################################
##########	URL Patters Class Based Views		###############
###########################################################################
from .views import(
	Posts_List,
	Posts_Create,
	Posts_Detail,
	Posts_Update,
	Posts_Delete,
	)

urlpatterns = [
	url(r'^$', Posts_List.as_view(), name='list'),
	url(r'^create$', Posts_Create.as_view(), name='create'),
	url(r'^(?P<id>\d+)/$', Posts_Detail.as_view(), name='detail'),
	url(r'^(?P<id>\d+)/update$', Posts_Update.as_view(), name='update'),
	url(r'^(?P<id>\d+)/delete$', Posts_Delete.as_view(), name='delete'),	
]


###########################################################################
##########	URL Patterns Function Based Views		###############
###########################################################################

# from .views import(
# 	posts_list,
# 	posts_create,
# 	posts_detail,
# 	posts_update,
# 	)

# urlpatterns = [
# 	url(r'^$', posts_list, name='list'),
# 	url(r'^create$', posts_create, name='create'),
# 	url(r'^(?P<id>\d+)/$', posts_detail, name='detail'),
# 	url(r'^(?P<id>\d+)/update$', posts_update, name='update'),
# ]

practice_copy/whiskey/project/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include("posts.urls", namespace="posts")),
    url(r'^users/', include("users.urls", namespace="users")),
]

practice_copy/whiskey/project/posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from .validators import *


# def min_validation(value):
# 	if len(value) < 5:
# 		raise ValidationError("{} is invalid, must have more than 5 characters". format(value))
# Create your models here.

class Post(models.Model):
	brand = models.CharField(max_length = 50, validators=[min_validation])
	brand_type = models.CharField(max_length = 80, validators=[min_validation])
	description = models.TextField(validators=[min_validation])
	price = models.DecimalField(max_digits = 6, decimal_places = 2)
	brand_email = models.EmailField(max_length = 50, blank=True)

	def __str__(self):
		return self.brand
		# return "{} {}".format(self.brand, self.brand_type)

	def get_absolute_url(self):
		
		return reverse("posts:detail", kwargs={"id":self.id})

practice_copy/whiskey/project/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
	
	class Meta:
		model = Post
		fields = [
			"brand",
			"brand_type",
			"description",
			"price",
			"brand_email"
		]

practice_copy/whiskey/project/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django import forms
from .models import Post
from posts.forms import PostForm
from django.views.generic import View
from django.core.exceptions import ValidationError

###########################################################################
##############		WE ARE CREATING CLASS BASED VIEWS 	###################
###########################################################################

class Posts_List(View):
	def get(self, req):
		whiskey_list = Post.objects.all()
		context = {
			"whiskey_list": whiskey_list,
		}
		return render(req, "posts/list.html", context)

class Posts_Detail(View):
	detail_template = 'posts/detail.html'

	def get(self, req, **kwargs):
		whiskey = get_object_or_404(Post, id=kwargs['id'])
		context = {
			"whiskey":whiskey
		}
		return render(req, self.detail_template, context)

# You can also use this to store your context
	# def get_context_data(self, **kwargs):

class Posts_Create(View):
	form_class = PostForm
	initial = {'key': 'value'}
	create_template = 'posts/create.html'

	def get(self, req, *args, **kwargs):
		create_form = self.form_class(initial=self.initial)
		context = {
			"create": create_form
		}
		return render(req, self.create_template, context)

	def post(self, req, *args, **kwargs):
		create_form = self.form_class(req.POST or None)
		# try:
		# 	if create_form.brand_email: 
		# 		print('da fuq is going on?')
		# except:
		# 	EmailValidator(
		# 	message="That is not a valid Email", 
		# 	code = None,
		# 	whitelist = None,)
		if create_form.is_valid():
			instance = create_form.save(commit=False)
			instance.save()
			return redirect(instance)
		context = {
			"create":create_form,
		}
		return render(req, self.create_template, context)

class Posts_Update(View):
	form_class = PostForm
	# initial = {'key': 'value'}
	update_template = 'posts/update.html'

	def get(self, req, *args, **kwargs):
		whiskey = get_object_or_404(Post, id=kwargs['id'])
		update_form = self.form_class(req.POST or None, instance = whiskey)
		context = {
			"whiskey": update_form
		}
		return render(req, self.update_template, context)

	def post(self, req, *args, **kwargs):
		whiskey = get_object_or_404(Post, id=kwargs['id'])
		update_form = self.form_class(req.POST or None, instance = whiskey)
		if update_form.is_valid():
			instance = update_form.save(commit=False)
			instance.save()
			return redirect(instance)
		context = {
			"whiskey":update_form,
		}
		return render(req, self.update_template, context)

class Posts_Delete(View):

	def get(self, req, **kwargs):
		instance = get_object_or_404(Post, id=kwargs['id'])		
		instance.delete()
		# have to set permanent to True
		return redirect('posts:list', permanent=True)






###########################################################################
############		WE ARE CREATING FUNCTION BASED VIEWS	###############
###########################################################################

# def posts_list(req):
# 	whiskey_list = Post.objects.all()
# 	context = {
# 		"whiskey_list" : whiskey_list,
# 	}
# 	return render(req, "posts/list.html", context)

# def posts_create(req):
# 	create_form = PostForm(req.POST or None)

# 	if create_form.is_valid():
# 		instance = create_form.save(commit=False)
# 		instance.save()
# 		# return HttpReponseRedirect(instance.get_absolute_url())
# 		return redirect(instance)
# 	context = {
# 		"create":create_form,
# 	}
# 	return render(req, "posts/create.html", context)

# def posts_detail(req, id=None):
# 	whiskey = get_object_or_404(Post, id=id)
# 	print(whiskey.id)
# 	context = {
# 		"whiskey": whiskey
# 	}
# 	return render(req, "posts/detail.html", context)

# def posts_update(req, id=None):

# 	whiskey = get_object_or_404(Post, id=id)

# # "initial" is a attribute of a form set?
# 	# update_form = PostForm(initial = {
# 	# 	"brand": whiskey.brand, 
# 	# 	"brand_type": whiskey.brand_type,
# 	# 	"price" : whiskey.price,
# 	# 	"description": whiskey.description
# 	# 	})
# # instance = whiskey is something learned from Jeff
# 	update_form = PostForm(req.POST or None, instance = whiskey)
# 	print(update_form)
# 	if update_form.is_valid():
# 		instance = update_form.save()
# 		# instance.save()
# 		return redirect(instance)
# 	context = {
# 		"whiskey": update_form,
# 	}

# 	# PostForm(data=request.POST)
# 	return render(req, "posts/update.html", context)

practice_copy/whiskey/project/posts/templates/posts/create.html
{% extends "base.html" %}
	
	{% block content %}
	
		<form action="" method="POST">{% csrf_token %}
			{{create}}

			<input type="submit" value="Create New Whiskey">
		</form>

	{% endblock content %}

practice_copy/whiskey/project/posts/templates/posts/detail.html
{% extends "base.html" %}

	{% block content %}

		<h4>{{whiskey.brand}}</h4>
		<h4>{{whiskey.brand_type}}</h4>
		<h4>{{whiskey.price}}</h4>
		<h4>{{whiskey.description}}</h4>
		


		<form action="{% url 'posts:update' whiskey.id %}">
			<input type="submit" value="UPDATE THIS WHISKEY">
		</form>

		<form action="{% url 'posts:delete' whiskey.id %}">
			<input type="submit" value="Delete this entry">
		</form>


		<form action="{% url 'posts:list' %}">
			<input type="submit" value="Back to list">
		</form>

	{% endblock content%}

practice_copy/whiskey/project/posts/templates/posts/list.html
{% extends "base.html" %}

{% block content %}

	<form action="{% url 'posts:create' %}">
			<input type="submit" value="Add a new entry">
	</form>
	

	{% for whiskey in whiskey_list %}
		<ul>
			<h3><a href="{{whiskey.id}}">{{whiskey.brand}}</a></h3>
			<li>{{whiskey.brand_type}}</li>	
			<li>{{whiskey.price}}</li>
			<p>{{whiskey.description}}</p>
		</ul>

	{% endfor %}


{% endblock content %}

practice_copy/whiskey/project/posts/templates/posts/update.html
{% extends "base.html" %}

	{% block content %}

		<form method="POST" action="">{% csrf_token %}

			<h4>{{ whiskey.brand.label_tag }}</h4>
			{{ whiskey.brand }}

			<h4>{{ whiskey.brand_type.label_tag }}</h4>
			{{ whiskey.brand_type }}

			<h4>{{ whiskey.price.label_tag }}</h4>
			{{ whiskey.price }}

			<h4>{{ whiskey.description.label_tag }}</h4>
			{{ whiskey.description }}


			<input type="submit" value="Update This Whiskey">
		</form>
	
	{% endblock content %}